### ISSUE TITLE
$groupsWithMembers is not filled when not including nested GroupMemberships

### ISSUE THREAD

**Issue by BFresco** [Tools4everBV/HelloID-Conn-Prov-Source-HelloID-RoleModel#6]
Noticed that the filling of the arraylist is only done in line 161, which is part of the $includeNestedGroupMemberships-collection only.

**Comment by rschouten97** [comment]
Hi @BFresco ,

Thanks for the feedback! This indeed is an issue, as it causes the content of the variable **$groupsWithMembers** to only be set when including nested group memberships.

So basically line 161: `[void]$groupsWithMembers.Value.Add($groupAugmented)` needs to move 2 lines down, to be outside of the if statement: `if ($includeNestedGroupMemberships -eq $true) {}`

I would like to ask for your feedback again on the proposed solution (where line 161 has been moved 2 lines down, to be outside of the if statement):
`
function Get-HelloIDGroupsWithMembers {
    param(
        [parameter(Mandatory = $true)]$Groups,
        [parameter(Mandatory = $true)]$Users,
        [parameter(Mandatory = $true)][ref]$groupsWithMembers
    )

    try {
        Write-Information "Retrieving group memberships for each HelloID group..." -InformationAction Continue

        $UsersGrouped = $Users | Group-Object userGuid -AsHashTable

        # Retrieve the membership of groups, requires fetch per group
        foreach ($group in $Groups) {
            $uriGroup = $uriGroups + "/" + $group.groupGuid
            Write-Verbose -Verbose:$verboseLogging "Getting group from $uriGroup"
            $groupAugmented = Invoke-RestMethod -Method Get -Uri $uriGroup -Headers $headers -UseBasicParsing
            $groupAugmented = $groupAugmented | Select-Object groupGuid, name, users, groups

            $groupAugmented | Add-Member -MemberType NoteProperty -Name "usersResolved" -Value $null -Force
            $usersResolved = New-Object System.Collections.ArrayList
            foreach ($user in $groupAugmented.users) {
                $userResolved = $UsersGrouped[$user] | Select-Object -First 1 -Property userName, userGuid

                [void]$usersResolved.Add($userResolved)
            }

            $groupAugmented.usersResolved = $usersResolved

            if ($includeNestedGroupMemberships -eq $true) {
                $groupAugmented | Add-Member -MemberType NoteProperty -Name "groupsResolved" -Value $null -Force
                $groupsResolved = New-Object System.Collections.ArrayList
                foreach ($group in $groupAugmented.groups) {
                    $groupResolved = $groupsGrouped[$group] | Select-Object -First 1 -Property name, groupGuid

                    [void]$groupsResolved.Add($groupResolved)
                }
                $groupAugmented.groupsResolved = $groupsResolved
            }

            [void]$groupsWithMembers.Value.Add($groupAugmented)           
        }
    }
    catch {
        $groupsWithMembers.Value = $null
        Write-Error $_.Exception
    }
}
`

**Comment by BFresco** [comment]
@rschouten97 I already did the same when troubleshooting. Seems to work from my end.
